version: '3.8'

services:
  rabbit:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: 12345
    ports:
      - 5672:5672
      - 15672:15672
